### PR TITLE
Remove `json-parse-even-better-errors`

### LINKED ISSUE #46: Remove `json-parse-even-better-errors`
As I understand. It

1. Add code point to unexpected token

```
parseJson('abcde')
Uncaught:
JSONError: Unexpected token 'a', "abcde" is not valid JSON while parsing 'abcde'
    at Module.parseJson (<CWD>/index.js:78:20)
    at REPL15:1:69 {
  fileName: undefined,
  codeFrame: undefined,
  rawCodeFrame: undefined
}
```

but it doesn't work anymore, since Node.js changed the error message.

Test case come from  https://github.com/npm/json-parse-even-better-errors/blob/25d9898034a1641a5bd3aa34446838a7932ee954/test/index.js#L161

This is a good feature, but we can do it in this code base ourself.

2. It add part of code to the message.

```
JSONError: Unterminated string in JSON at position 11 while parsing '{"foo: bar}'

> 1 | {"foo: bar}
    |            ^
```

We already have code frame in the message, it seems unnecessary. Even confusing some time.

```
"abcde" is not valid JSON while parsing 'abcde'
```

### PR DESCRIPTION
**Pull request by fisker**
Fixes #46

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -1,7 +1,11 @@
-import fallback from 'json-parse-even-better-errors';
 import {codeFrameColumns} from '@babel/code-frame';
 import indexToPosition from 'index-to-position';
 
+const getCodePoint = character => {
+	const codePoint = character.codePointAt(0).toString(16).toUpperCase();
+	return '0x' + (codePoint.length % 2 ? '0' : '') + codePoint;
```
Comment (sindresorhus) [inline index.js:6]: I prefer showing it as a Unicode escape: https://github.com/sindresorhus/unicode-escapes/blob/ceb0401f6914ca1291819eb2822c38dd6294b8fb/index.js#L13

Comment (fisker) [reply index.js]: DONE.

**Comment by sindresorhus** [comment]
Thanks 🙏
